### ISSUE TITLE
Material binding not displaying with ARKit after performing a glTF to USDZ conversion

### ISSUE THREAD

**Issue by lanxinger** [pablode/guc#28] opened 2024-07-10 12:16 UTC
Moved over from a discussion on the Alliance for Open USD forum:
https://forum.aousd.org/t/obj-gltf-to-usdz-usdzconvert-discontinued/1648/9

Material bindings are set to preview after performing a glTF to USDZ conversion with guc and
iOS ARKit/RealityKit/SceneKit doesn't display the materials on the model as a result. 

The model does display view the Storm Renderer used in macOS Preview though.

![iOS_RealityKit_QuickLook](https://github.com/pablode/guc/assets/20549552/06aff3d7-d85c-415a-b433-5fa7403904d1)
<img width="1136" alt="macOS_Preview" src="https://github.com/pablode/guc/assets/20549552/eab789ef-ef97-4b9e-ba25-4ea6b5a7ae85">

`rel material:binding:preview = </Asset/Materials/UsdPreviewSurface/Materials/Texture>
`
changing that to
`rel material:binding = </Asset/Materials/UsdPreviewSurface/Materials/Texture>`
works as expected.

I furthermore found the face normals get modified to flat shading during that conversion:

<img width="780" alt="before" src="https://github.com/pablode/guc/assets/20549552/608034b7-04a9-4177-9cd4-514d6f8d6fc3">
<img width="759" alt="after" src="https://github.com/pablode/guc/assets/20549552/29f8919f-8f96-46c1-9868-64f2cf2278f6">

Here is the link the the USDZ model:
[https://drive.proton.me/urls/DJ0SRP3N44#20IZrmyz28Zy](https://drive.proton.me/urls/DJ0SRP3N44#20IZrmyz28Zy)

Input glTF binary:
[https://drive.proton.me/urls/X9A1TRZN5G#HirzCL9ik1BG](https://drive.proton.me/urls/X9A1TRZN5G#HirzCL9ik1BG)

**Comment by pablode** [comment] 2024-07-13 11:30
Hi! Thanks for the report.

As Dhruv says, this sounds like an iOS/Apple specific bug where the runtime does not fall back to the preview binding. guc should also author the default material binding instead.

I'll investigate the normal issue and keep you posted.

**Comment by pablode** [comment] 2024-07-13 19:08
@lanxinger I've implemented the binding fix and am planning to release a new version in the next few days. 

Unfortunately, I can't see any issue with the normals. Could you elaborate how the above screenshots were created? Also, could you verify that (if you used usdview) 'Flat Shaded' is not enabled?

<img width="1117" alt="Screenshot 2024-07-13 at 21 05 15" src="https://github.com/user-attachments/assets/f61ea15c-6e2b-497f-9c52-6acd46687ba4">

**Comment by lanxinger** [comment] 2024-07-14 07:44
hi @pablode thank you for the quick action.

the screenshots above are from blender actually. I haven't tried usdview but good to know it is working properly there. 

I am unable to change the shading to smooth inside blender for this model. maybe another ticket I need to file there for that. However it does seem to work properly for the initial USDZ we get from object capture:
https://drive.proton.me/urls/ZYSW6YM7NW#XN8F3uwqvBMy

**Comment by pablode** [comment] 2024-07-14 09:42
I think this may be a Blender issue based on following observations:
- Adobe USD-Fileformat-plugins produces a file that has the same problem
- Doing a roundtrip (GLB -> USDC -> GLB) using above plugin results in a GLB with smooth normals in Blender
- If I export the GLB as USDZ using Blender and drop it into usdz-viewer.net, it has flat shading

Perhaps this issue is related? https://projects.blender.org/blender/blender/issues/107696

Will try to verify with NVIDIA Omniverse.

**Comment by pablode** [comment] 2024-07-14 17:14
Looks correct in Omniverse.. at least the normals.

![2024-07-14 19_11_44-USD Composer 2023 2 5 Beta - C__Users_pablode_Downloads_test usdz_](https://github.com/user-attachments/assets/283ac09e-ed29-43af-95b1-5a2069607a69)

Interestingly, the three NVIDIA render delegates didn't fall back to the preview material binding, too.

**Comment by lanxinger** [comment] 2024-07-15 06:17
thanks @pablode for the thorough investigation. I have also suspected a blender bug for this. maybe I can contribute this issue to the filed ticket you linked above. 

I wonder if the fallback to the preview material binding is somewhat related to the USD version being used in the build.

I see that in Apple's case it's  reported as Apple USD Tools (0.24.3) which means it's one release behind the latest 0.24.5. 

Maybe also worth filing this on the USD GitHub?

**Comment by pablode** [comment] 2024-07-15 19:58
The binding issue should be fixed in 0.4, thanks for reporting!

Regarding the behaviour in USD: I don't think it's related to any version. My hunch is that it's caused by the [HdRenderDelegate::GetMaterialBindingPurpose()](https://github.com/PixarAnimationStudios/OpenUSD/blob/2864f3d04f396432f22ec5d6928fc37d34bb4c90/pxr/imaging/hd/renderDelegate.h#L411) getter, which allows the renderer to only return `full` or `preview` (unlike `GetMaterialRenderContexts`, where a preference list is returned).

**Closed** 2024-08-08 06:14 UTC
